"""adds Vocablist  and Word models

Revision ID: 31dc53652495
Revises: 
Create Date: 2022-01-27 12:45:34.442128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31dc53652495'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vocablist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('word',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('selected_word', sa.String(), nullable=True),
    sa.Column('translation', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('vocablist_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vocablist_id'], ['vocablist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word')
    op.drop_table('vocablist')
    # ### end Alembic commands ###
